112 author doc
hlxsites/sazerac-wheatleyvodka pull request #130
Opened 2023-09-13 15:11 UTC by chhaack

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs (without age check):
- Before: https://main--sazerac-wheatleyvodka--hlxsites.hlx.page/?noAgeCheck=yes
- After: https://112-author-doc--sazerac-wheatleyvodka--hlxsites.hlx.page/?noAgeCheck=yes

Test URLs (with age check):
- Before: https://main--sazerac-wheatleyvodka--hlxsites.hlx.page/
- After: https://112-author-doc--sazerac-wheatleyvodka--hlxsites.hlx.page/

2023-09-14 13:09 UTC, karlpauls requested changes
Looks good, I added some minor comments - could you have a look?

2023-09-14 13:09 UTC, karlpauls commented on docs/blocks/ageverification.md
> +The age verification block is automatically integrated into every page delivered if the cookie sazAgeOK is missing.<br>
Can you try to explain it a bit more - just another sentence or two about how the cookie is working and what happens with accepting vs rejecting the question (redirect etc.).

2023-09-14 13:09 UTC, karlpauls commented on docs/blocks/buy-template.md
> +Definition of the output of the buy block. Authoring has to done via templates/buy.docx.
"has to done via" => "has to be done via"

Might be worthwhile to mention explicitly that these are files in Sharepoint (in the other cases as well).

2023-09-14 13:09 UTC, karlpauls commented on docs/blocks/pocketguide.md
> +download block for the pocket guide pdf
Maybe it shouldn't say "download" but "insert" or even just remove it and just say: "block for"

2023-09-14 13:09 UTC, karlpauls commented on docs/blocks/columns.md
> +## Columns
Can you double check if we have different variants of the columns block we use? I think we have at least the case where it is making the image a background image and another one where we can reverse the way we break the columns.

2023-09-14 14:43 UTC, chhaack commented on docs/sections-metadata.md
> +# Section Metadata
only found column block using section metadata at the moment

2023-09-15 06:54 UTC, RemoLiechti commented on docs/blocks/recipes.md
> +
created by missing, see some other cocktails

2023-09-18 07:00 UTC, RemoLiechti commented
Issues found:

**For the cocktail detail page (receipe)**
I added a proposal for the missing creator information to the receipes.md. Use the flatiron flip cocktail for details: https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B6090EA25-73A7-48BF-824B-7599FC820F44%7D&file=flatiron-flip.docx&action=default&mobileredirect=true

1. add the creator information to the documentation
2. update the three screenshots with the flatiron flip instead
3. describe the templating mechanism, showing the content of the template, where the template is stored, how to change it. The template needs to be published individually to reflect any changes online.

**different ways of describing**
Various ways on how content shall be structured found. This may confuse the reader, i.e if he needs to put special characters. Stick to one consistent way of notation across all documentation.

- (img) vs image vs [image]
- list vs (ul)(li)entry(li)entry vs (List with links)
- (a) vs [links] vs (embed link) vs link
- text vs [text]
- (h1) vs title

2023-09-21 08:04 UTC, karlpauls approved these changes

2023-09-21 08:04 UTC, merged